services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - db

  db:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    ports:
      - '1433:1433'
    volumes:
      - /var/opt/mssql
      - ./sql:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      SA_PASSWORD: 'Password1234!'
      ACCEPT_EULA: 'Y'
