# Followed guide here
# https://www.geeksforgeeks.org/execution-of-c-program-using-docker-environment/
FROM gcc:latest

COPY . /DockerWorld

WORKDIR /DockerWorld/

RUN gcc -o DockerWorld dockerworld.c

# The guide was a bit messed up here and missed one level of directories
CMD ["/DockerWorld/DockerWorld"]
