# Many awesome lua templates available at this link for various versions and systems
# https://hub.docker.com/r/nickblah/lua
FROM nickblah/lua:latest

COPY . /LuaTest

ENV NAME=Derek

CMD ["lua","/LuaTest/helloworld.lua"]
